name: "Healthy - development"

# only execute workflow on the master branch
on:
  push:
    branches: main

jobs:
  buildAndPublish:
    name: Build and publish dev docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # build dmarc-monitor image and push it to docker hub
      - name: Build and push dmarc-monitor image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dmarc-monitor:dev
