name: "DMARC-monitor - releases"

# only execute workflow on the master branch
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  dmarc-monitor:
    name: Build and publish dmarc-monitor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # build dmarc-monitor image and push it to docker hub
      - name: Build and push dmarc-monitor image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dmarc-monitor:${{ env.RELEASE_VERSION }}

  release_dmarc-monitor:
    name: Release dmarc-monitor
    runs-on: ubuntu-latest
    needs: [dmarc-monitor]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # release a new version on github
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: none
          RELEASE_NAME_PREFIX: "Release "
